version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/jotter-api/
hooks:
  AfterInstall:
    - location: script/install_dependencies
      timeout: 100
      runas: root
  ApplicationStart:
    - location: script/start_server
      timeout: 100
      runas: root