version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/jotter-api/
    overwrite: true
hooks:
  BeforeInstall:
    - location: script/before_install.sh
      timeout: 300
      runas: root
# During the AfterInstall deployment lifecycle event, run the commands 
#   in the script specified in "location".
  AfterInstall:
    - location: script/after_install.sh
      timeout: 300
      runas: root
# During the ApplicationInstall deployment lifecycle event, run the commands 
#   in the script specified in "location".
  ApplicationStart:
    - location: script/application_start.sh
      timeout: 300
      runas: root