version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/jotter-api/
    overwrite: true
hooks:
  AfterInstall:
    - location: script/install_dependencies.sh
      timeout: 100
      runas: root
  ApplicationStart:
    - location: script/start_server.sh
      timeout: 100
      runas: root